---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}
inputs:
- name: builder-src
- name: input-stemcell
outputs:
- name: light-stemcell
run:
  path: builder-src/ci/tasks/build.sh
params:
  ami_description:         ""
  ami_virtualization_type: ""
  ami_visibility:          ""
  ami_region:              ""
  ami_access_key:          ""
  ami_secret_key:          ""
  ami_bucket_name:         ""
  ami_destinations:        ""
