---
platform: linux
image: docker:///boshcpi/aws-light-stemcell-builder
inputs:
- name: builder-src
- name: heavy-stemcell-in
outputs:
- name: light-stemcell-out
run:
  path: builder-src/ci/tasks/build.sh
params:
  access_key: replace-me
  secret_key: replace-me
  bucket_name: replace-me
  region: replace-me
  copy_dests: replace-me
  ami_description: replace-me
  ami_is_public: replace-me
  ami_virtualization_type: replace-me
