---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}
inputs:
- name: builder-src
run:
  path: builder-src/ci/tasks/test-drivers.sh
params:
  access_key:                 ""
  secret_key:                 ""
  bucket_name:                ""
  region:                     ""
  copy_region:                ""
  ami_fixture_id:             ""
  existing_volume_id:         ""
  existing_snapshot_id:       ""
  uploaded_machine_image_url: ""
